Update build.yaml to last chip-build version
agners/matter-linux-example-apps pull request #2
Opened 2024-11-12 08:34 UTC by lboue

Update build.yaml to last chip-build version:

https://github.com/project-chip/connectedhomeip/pkgs/container/chip-build/232396506?tag=91

2025-05-06 19:44 UTC, agners requested changes
To make sure the example apps work on Debian (which the development add-on is based on) it would be better to use the Debian based chip-build container from the wheels project (https://github.com/home-assistant-libs/chip-wheels/), similar to how I've done it with the OTA Provider app: https://github.com/home-assistant-libs/matter-linux-ota-provider/pull/3/commits/8a8c003f15890d70773ca0edc1e33cc699f6878f.

2025-05-09 17:25 UTC, lboue commented
Is it OK now?

2025-07-07 19:29 UTC, lboue commented
Is it OK now?
It could help to implement RVC service area cluster.

2025-07-07 19:32 UTC, agners approved these changes

2025-07-07 19:32 UTC, merged